# Called by ci.yml to perform dotnet format linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Lint - dotnet format

on:
  workflow_call:

permissions: {}

jobs:
  run-dotnet-format:
    name: 'Run dotnet format (${{ matrix.name }})'
    runs-on: windows-2025

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stable
            expose-experimental-features: false
          - name: unstable
            expose-experimental-features: true

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: dotnet restore
      run: dotnet restore efinanceira/EFinanceira.sln

    - name: dotnet format
      shell: pwsh
      env:
        ExposeExperimentalFeatures: ${{ matrix.expose-experimental-features }}
      run: |
        dotnet format efinanceira/EFinanceira.sln --no-restore --verify-no-changes
